[package]
name = "owshen"
version = "0.1.0"
edition = "2021"

[dependencies]
ff = { version = "0.13.0", features = ["derive"]}
bindings = { path = "./bindings" }
ethers = { version = "2", default-features = false, features = ["rustls"] }
eyre = "0.6"
tokio = { version = "1.30.0", features = ["macros", "rt", "rt-multi-thread"] }
rand = "0.8"
num-bigint = "0.4"
tempfile = "3"